---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-namespaces
rules:
  - apiGroups: ["*"]
    resources: ["namespaces", "namespaces/status"]
    verbs: ["watch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-namespaces-binding
subjects:
  - kind: User
    name: lukasz@blablabla.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-namespaces
  apiGroup: rbac.authorization.k8s.io
